# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

type_list = [
	["com" , "Semi Hermeticos","com/compresorSH.jpg", "<b>Compresores semi-herméticos de pistón Dorin , para refrigeración y aire acondicionado.</b></br></br> - Alta eficiencia; modelos para refrigerantes R-22, R-134a, R-404 y R-507 </br> - Fabricados bajo rigurosas normas internacionales de diseño y control en Italia</br> - Desde 1.5 a 75 HP en stock para entrega inmediata</br> - Disponibles en 220 y 380 V</br> - Completa línea de repuestos en stock para su reparación .</br> - Para alta, media y baja temperatura de evaporación."],
	["com" , "Hermeticos" ,"com/compresorH.jpg", "<b>Compresores-herméticos de pistón Maneurop - Bristol - Copeland - Tecumseh , para refrigeración y aire acondicionado.</b></br></br> - Alta eficiencia; modelos para refrigerantes R-22, R-134a, R-404 y R-507 </br>- Fabricados bajo rigurosas normas internacionales de diseño y control .</br> - Desde 1.5 a 13 HP en stock para entrega inmediata</br> - Disponibles en 220 y 380 V</br> - Para alta, media y baja temperatura de evaporación."],
	["com", "Scroll","com/compresorSCroll.jpg", "- Línea de compresores herméticos tipo Scroll, para aplicaciones de alta y media temperatura.</br> - Modelos Scroll y Rotativos Panasonic , ZR (R-22) ; ZP (R-410) ; SM (R-22): SZ (R-407)</br> - Capacidad desde 9.000 BTU hasta 180.000 BTU"],
	["com", "Fraccionarios" ,"com/compresorFrac.png", "<b>Línea de compresores fraccionarios Embraco - Aspera</b></br></br> - Compresores para media y baja temperatura con gas R-134a.R-22; R-507 O R-404</br> - Modelos en 220 V a 50 Hz.</br> - Modelos de 1/6+ a 1.5 HP.</br>- Rendimiento de +5°C a -35°C. </br> </br><b>Línea de compresores fraccionarios Danfoss:</b></br> </br> - Compresores para alta, media y baja temperatura con gas R-134a R-507</br> - Modelos en 220 V a 50 Hz.</br> - Modelos de 1/4+ a 3/4+ HP.</br> - Rendimiento de +15°C a -35°C. "],
	["eva", "Evaporadores Linea HEA" ,"evap/evaHEA.png", "<b>Características Generales:</b></br></br>Nuestros paquetes aleteados de alta eficiencia están fabricados con aletas de aluminio de perfil y tubo de cobre de 12 mm de alta calidad. Los intercambiadores de calor se suministran limpios en el interior de las tuberías y probados a una presión de 30 bars.</br></br><b>La Carcasa:</b></br></br> De aluminio pintado blanco al polvo electrostático, con alta resistencia contra la corrosión y los impactos. No produce residuos tóxicos.</br></br><b>Los ventiladores:</b></br></br>Todos con motor axial de rotor externo de alto estándar de seguridad y adaptados a la carcasa con un sistema anti vibración.</br></br><b>Sistema de des escarche:</b></br></br>Proporcionado por resistencia de acero inoxidable enfundadas en tubos de aluminio localizados en el paquete aleteado y en la bandeja de desagüe.</br></br><b>Instalación y Partes eléctricas:</b></br></br>Conexión a toma de tierra, instalada en caja de conexiones con agujeros de acceso equipados con sistema de estanqueidad. Todo el material seleccionado cuidadosamente para su fiabilidad a largo plazo."],
	["eva", "Evaporadores Linea HED" ,"evap/evaHED.png", "<b>Características Generales:</b></br></br>Nuestros paquetes aleteados de alta eficiencia están fabricados con aletas de aluminio de perfil y tubo de cobre de 12 mm de alta calidad. Los intercambiadores de calor se suministran limpios en el interior de las tuberías y probados a una presión de 30 bars.</br></br><b>La Carcasa:</b></br></br> De aluminio pintado blanco al polvo electrostático, con alta resistencia contra la corrosión y los impactos. No produce residuos tóxicos.</br></br><b>Los ventiladores:</b></br></br>Todos con motor axial de rotor externo de alto estándar de seguridad y adaptados a la carcasa con un sistema anti vibración.</br></br><b>Sistema de des escarche:</b></br></br>Proporcionado por resistencia de acero inoxidable enfundadas en tubos de aluminio localizados en el paquete aleteado y en la bandeja de desagüe.</br></br><b>Instalación y Partes eléctricas:</b></br></br>Conexión a toma de tierra, instalada en caja de conexiones con agujeros de acceso equipados con sistema de estanqueidad. Todo el material seleccionado cuidadosamente para su fiabilidad a largo plazo."],
	["eva", "Evaporadores Linea HEJ" ,"evap/evaHEJ.png", "<b>Características Generales:</b></br></br>Nuestros paquetes aleteados de alta eficiencia están fabricados con aletas de aluminio de perfil especial y tubo de cobre de 9.52 mm de alta calidad. Los intercambiadores de calor se suministran limpios en el interior de las tuberías y probados a una presión de 30 bars.</br></br><b>La Carcasa:</b></br></br>De aluminio pintado blanco al polvo electrostático, con alta resistencia contra la corrosión y los impactos. No produce residuos tóxicos. Desde 630mm en acero galvanizado.</br></br><b>Los ventiladores:</b></br></br>Todos con motor de Espiral de Sombra con alto estándar de seguridad y adaptados a la carcasa con un sistema anti vibración.</br></br><b>Sistema de des escarche:</b></br></br>Proporcionado con calentadores de acero inoxidables Zoppas.</br></br><b>Instalación y Partes eléctricas:</b></br></br>Conexión a toma de tierra, instalada en caja de conexiones con agujeros de acceso equipados con sistema de estanqueidad. Todo el material seleccionado cuidadosamente para su fiabilidad a largo plazo."],
	["eva", "Evaporadores Linea HEC" ,"evap/evaHEC.png", "Nuestros evaporadores de alta eficiencia están fabricados con aletas de aluminio y tubo de cobre de 12mm de alta calidad, los intercambiadores de calor se suministran limpios y probados con una presión de 30 bars.</br></br> De aluminio pintado blanco al polvo electrostático, con alta resistencia contra la corrosión y los impactos.</br></br> Sistema de desescarche por resistencias eléctricas de acero inoxidable enfundadas en tubos de aluminio localizados en el paquete aleteado y en la bandeja de desagüe. "],
	["eva", "Evaporadores Linea HEB" ,"evap/evaHEB.png", "Nuestros evaporadores de alta eficiencia están fabricados con aletas de aluminio y tubo de cobre de 12mm de alta calidad, los intercambiadores de calor se suministran limpios y probados con una presión de 30 bars.</br></br> De aluminio pintado blanco al polvo electrostático, con alta resistencia contra la corrosión y los impactos.</br></br> Sistema de desescarche por resistencias eléctricas de acero inoxidable enfundadas en tubos de aluminio localizados en el paquete aleteado y en la bandeja de desagüe. "],
	["con", "Condensadores" ,"cond/con1.png" , "Nuestros condensadores de alta eficiencia, están fabricados con aletas de aluminio y tubo de cobre de 9.52mm de alta calidad.  Los intercambiadores de calor se suministras limpios en el interior de las tuberías y con una prueba de presión de 30bars.</br></br> La carcaza de acero galvanizado pintado en negro al polvo electrostático, con alta resistencia contra la corrosión y resistente a los impactos no produce residuos tóxicos. </br></br> Los ventiladores con motor axial y rotor externo, con alto estándar de seguridad y anclados a la carcaza."],
	["fil", "Filtros secadores DCL" , "fil/filtrodml.png", "Los filtros secadores DCL-DML para las lineas de liquido, protegen los sistemas de refrigeración y de aire acondicionado contra la humedad, las partículas solidas y los ácidos. Con la eliminación de estas fuentes de contaminación, las instalaciones están mejor protegidas contra las dañinas reacciones químicas y las partículas abrasivas.</br></br><b>Aplicaciones :</b></br></br>-Refrigeración tradicional</br>-Unidades de aire acondicionado</br>-Refrigeración para el transporte</br></br></br><b>Ventajas:</b></br></br>-Gran capacidad de absorción de humedad, cuatro veces mayor que los secadores de alúmina activada tradicional</br>-Gran capacidad de secado que evita el riesgo de formación de ácido en el sistemas de refrigeración o aire acondicionado</br>-Conectores de acero tratados con cobre ; no se necesita paño húmedo al soldar</br>"],
	["fil", "Filtros con nucleo intercambiable" , "fil/filtrodlc.png", "Los filtros secadores con núcleo intercambiable protegen los sistemas de refrigeración y aire acondicionado de la humedad, de ácidos y partículas solidas. Están equipados con núcleos de 1, 2 o 3 elementos en su interior y se pueden utilizar  tanto en la linea de liquido como en la de succión, en instalaciones de uno o varios compresores . El núcleo solido garantiza una alta capacidad de secado y evita la formación de ácidos en el sistema.</br></br><b>Aplicaciones:</b></br></br>-Instalaciones comerciales con refrigerantes fluorados o CO2.</br>-Instalaciones industriales con refrigerantes fluorados o CO2.</br></br><b>Ventajas:</b></br></br>-Alta capacidad de retención de suciedad en la lineas de aspiración y de liquido.</br>-Puede utilizarse en cualquier entorno incluidas las aplicaciones marítimas.</br>-puede montarse en cualquier posición.</br></br><b>Datos técnicos:</b></br></br><b>48-DC :</b> Núcleo para las lineas de liquido (80% molecular sieves y 20% alúmina activada `para CFC y HCFC). Adsorbe eficazmente la humedad y ácido del sistema.</br></br><b>48-DA :</b> Núcleo para las lineas de aspiración después de la combustión en el compresor (30% molecular sieves y 70% alúmina activada para CFC y HCFC).</br></br><b>48-F :</b> Para la tubería de aspiración elimina todas las partículas solidas del sistema."],
	["ven" , "Ventiladores", "ven/ven1.png", "<b>Ebmpapst</b></br> </br> - Diámetros desde 250 mm hasta 800 mm</br> - Modelos en 220 V y 380 V, 24 50 y 60 Hz. </br> - Flujo de aire Aspirante o Impelente.</br> - Fabricados en Alemania</br> </br><b>Ziehl Abegg</b></br> Desde 450 mm hasta 800 mm de diámetro en stock.</br></br> - Distintos tipos, caudales de aire y presiones estáticas.</br> - Modelos en 220 V y 380 V, 50 y 60 Hz.</br> - Empleo en instalaciones DE MANTENCION Y BAJA TEMPERATURA.</br> - Flujo de aire Aspirante o Impelente (según tipo).</br> - Fabricados en Alemania.</br> </br><b>W.G</b></br> Diámetros desde 250 mm hasta 800 mm.</br></br> - Modelos en 220 V y 380 V, 50 Hz. </br> - Flujo de aire Aspirante o Impelente.</br> - Fabricados en China."],
	["ace" , "Aceite mineral Suniso", "ace/aceSuniso.jpg", "Aceite suniso, producido bajo estrictas nrmas de fabricación internacionales, esta diseñado para el cuidado y buen funcionamiento de las partes mecánicas del compresor.</br> Aceite 3GS, 4GS, 5GS.</br> En bidones de 4 litros y en tarros de 20 litros.</br> Aceite mineral para utilizarlo con gases tradicionales.</br> Fabricados en USA</br> Completo stock para entrega inmediata"],
	["ace" , "Aceite Sintético", "ace/aceEmkarate.jpg", "<b>Aceite sintético</b></br></br> -RL-32 ; RL-46; SL-68-RL-100</br> -En formato de 1 y 4 litros</br> -Aceite diseñado para refrigerantes ecológicos.</br> -Fabricados en USA</br></br> Completo stock para entrega inmediata."],
	["ace" , "Para bomba de vacío", "ace/aceVacio.jpg", "<b>Aceites para bombas de vacío:</b> Línea de aceites que protegen y cuidan la bomba de vacío. Su presentación  es en botellas de 1 litro</br></br>PRO-SET Premium vacío de bomba de aceite es una calidad muy alta, es compatible para su uso en bombas hechas por la mayoría de los fabricantes de bombas de vacío, el aceite siempre debe estar limpio y libre de contaminantes tales como humedad, ácidos, vapores, polvo, etc.</br></br>Se recomienda  cambiar el aceite de la bomba de vacío después de cada uso para mejorar el servicio y la vida de la bomba."],
	["ace" , "Detergentes y Kit de acidez", "ace/detergente.jpg", "<b>Acti-Brite</b></br></br>Detergente ácido de alta espuma para ser usado en exteriores. Está diseñado para remover la contaminación desde la superficie de los intercambiadores de calor y aumentar la eficiencia del flujo de aire. El líquido penetra profundamente por los rincones de los serpentines, dónde la espuma remueve la suciedad como pelusas, pasto, hojas, insectos, plumas y hollín hacia afuera para ser fácilmente enjuagado con agua. Según aplicación, puede diluirse entre 1 a 10 partes de agua por una parte de Acti-Brite.</br></br><b>Acti-Klean</b></br></br>Potente combinación concentrada de detergente y ablandador para la limpieza de serpentines de evaporadores, ayudando a restaurar la eficiencia del sistema. De acción rápida, biodegradable, no tóxico y fácil de usar. Su uso periódico previene acumulaciones de suciedad causante de olores y mal funcionamiento de los serpentines. Remueve grasa, barro, aceite, pelusas y pelo. No requiere de enjuague. (para cumplir la norma USDA, el serpentín debe ser enjuagado con agua potable).Según aplicación, puede usarse sin diluir o diluirse hasta en 6 partes de agua por una parte de Acti-Klean.</br></br><b>Kit de prueba Virginia ETK</b></br></br>El kit de prueba de acidez Virginia ETK es la manera mas simple para determinar si el nivel de acidez del compresor de lubricantes de poliol ester (POE) es considerado seguro o es muy ácido.</br></br>Características:</br>- El cambio de color ultra-sensible entrega una indicación exacta.</br>- Tabla de color comparativa de cada caja.</br>- Uso económico.</br>- Fabricado en U.S.A."],
	["ter" , "Microprocesador", "ter/terMic.jpg", "<b>Microprocesadores</b></br></br>La serie de controladores dispuestos en nuestras instalaciones, pueden usarse para una gran variedad de aplicaciones de refrigeración, desde el control de temperatura y desescache hasta aplicaciones mas avanzadas, como el control de iluminación y ventilador.</br></br>- Modelos con 2 sondas y 3 relays *</br>- Control integral de temperatura, ventiladores y calefactores de deshielo.</br>- Posibilidad de realizar el deshielo manual.</br>- Alimentación: 12V o 220 V.</br>- Diferencial de 0.1 a 20 °C.</br>- Alarma de alta o baja temperatura.</br>- Rango de temperatura de -50 a +150 °C *</br>- Instalación a embutir.</br>- Programación vía copy key.*</br>- Utiliza sondas PTC / NTC.</br></br>*Características dependiendo de la marca y el modelo a elegir."],
	["ter" , "Termometros y Termostatos", "ter/terTer.jpg", "<b>Termostatos digitales y análogos con una salida.</b></br></br>Aplicación tanto para refrigeración como para calefacción.</br></br><b>Digitales</b></br>- Configurable como control para refrigeración o calefacción.</br>- Termostato de 1 relay de salida.</br>- Alimentación: 12V y 220V.a.c. 50/60 Hz.</br>- Rango Control: -50 a +150ªC</br>- Montaje sobre puesto o embutido. </br></br><b>Analogos</b></br>-Termómetros."],
	["ter" , "Presostatos", "ter/terPres.jpg", "<b>Presostatos</b></br></br>Los presostatos son utilizados en los sistemas de refrigeración como elementos de protección contra presiones de aspiración demasiado bajas o excesivas, arrancando y parando compresores así como ventiladores de condensadores, Funcionan cerrando o abriendo el circuito dependiendo de las fluctuaciones de presión que se encuentren el el sistema.</br></br><b>Descripción presostatos digitales:</b></br></br>- Control de presión de succión o descarga en sistemas de refrigeración</br>- Manómetro digital</br>- Rango de presión de 0 a 500 psi.</br>-Sondas de presión de alta y baja.</br></br></b>Descripción presotatos mecánicos:</b></br></br>- Para baja, alta y alta-baja temperatura.</br>- Con reset manual y automático.</br>"],
	["cyb" , "Cierres y Bisagras", "cyb/cyb1.png", "La gama de cerrojos, bisagras y cierres de correderas, dispuestos en nuestra instalación, cubren la gran demanda que exige el mercado actual manteniendo un variado stock para instalaciones comerciales, semi industriales e Industriales.</br></br> Importamos nuevos productos para ofrecer una mejor calidad de estos a nuestros clientes."],
	["ais" , "Aislacion de Tuberia", "ais/aisTub.jpg", "En tiras de 2 mts de largo.</br>- Diámetros de 1/4\" hasta 3.1/8\" mm.</br>- Espesores de 3/8\",  1/2\",  3/4\"</br></br><b>Características generales:</b></br></br>La aislación para tuberías está especialmente concebida para la refrigeración y climatización, Es ideal para evitar la formación de escarcha en los ductos de agua fría. Reduce los problemas ocasionados por pérdidas térmicas de condensación en enfriadores de agua y líneas frigoríficas.</br></br><b>Otras características son:</b></br></br>-Producto no inflamable, libre de CFCs, no daña la capa de ozono.</br>- Excepcional resistencia a los cambios climáticos y a la radiación ultravioleta.</br>- Resistencia a la humedad y al vapor</br>- Coeficiente de conductividad térmica tipo K</br>- Fácil de instalar y permite excelentes terminaciones.</br>*Manejamos stock disponible en forma permanente, para la entrega inmediata."],
	["ais" , "Aislacion en Plancha", "ais/aisPlan.jpg", "Rollos de 1, 4 metro de ancho por diferentes largos</br>- Espesores de 13mm; 19mm y 25mm</br>- Ventas por metro</br></br><b>Características generales:</b></br></br>- Coeficiente de conductividad térmica (K) </br>- Fácil de instalar y permite excelentes terminaciones..</br>- Excepcional resistencia a los cambios climáticos y el sol.</br>- Producto no inflamable, libre de CFCs, no daña la capa de ozono.</br>*Manejamos stock disponible en forma permanente, para la entrega inmediata."],
	["ais" , "Accesorios de Aislacion", "ais/aisAcc.jpg", "<b>Cinta aislante autoadhesiva:</b></br></br>Fabricada con el mismo material que la aislación .Ideal para aislar tuberías, válvulas y fittings. Muy fácil de usar, excelente para prevenir problemas de condensación. Específicamente diseñada para retardar la pérdida de calor en tuberías calientes y para prevenir la absorción de calor o la formación de escarcha en las tuberías frías o líneas de refrigeración.</br></br>Descripción:</br>- Rollos de 10 metros de largo</br>- Ancho: 2,5\"</br>- Espesor: 3 mm.</br>- Gran adherencia al metal.</br>- Previene el goteo por efecto de la condensación.</br></br><b>Pegamento:</b></br></br>Adhesivo de contacto de neopreno modificado, especialmente formulado para su empleo con la aislación Aeroflex, aunque también es aplicable a otro tipo de materiales.Posee una alta resistencia al vapor de agua y buenas propiedades protectoras, previniendo que agua y humedad penetren por los puntos de unión. Se sugiere su aplicación en lugares ventilados, evitando su inhalación. Es inflamable en estado líquido, pero una vez seco se comporta como adhesivo auto extinguible.</br></br>Descripción:</br>- Tipo: neopreno.</br>- Apariencia: líquido negro.</br>- Rendimiento: 3 a 4.5 m2 por litro.(aplicando adhesivo por ambas caras)</br>- Otros usos: para pegar metales, gomas, formalita, melamina, corcho.</br></br><b>Cinta de aluminio con adhesivo:</b></br></br>Excelente para ser usada como sellante de vapor en ductos de fibra de vidrio y metal.Ideal también para utilizarla en terminaciones o como sellante sobre cualquier superficie seca y limpia.</br></br>Descripción:</br>- Rollos de 30 metros</br>- Ancho: 50 mm.</br>- Espesor: 35 micrones."],
	["ref" , "Refrigerantes", "ref/ref1.png", "<table><tr><th>Refrigerante</th><th>Peso neto Kg</th><th>Aplicación</th></tr><tr><td>R-22</td><td>13,6</td><td>Refrigeración comercial e industrial AC</td></tr><tr><td>R-134a</td><td>13,6</td><td>AC automotriz y refrigeración comercial</td></tr><tr><td>R-134a</td><td>0,227</td><td>Gas en lata de 227 gramos (8 o.z)</td></tr><tr><td>R-141b</td><td>13,6</td><td>Limpieza de sistemas HVAC</td></tr><tr><td>R-404a</td><td>10,9</td><td>Baja temperatura de refrigeración</td></tr><tr><td>R-406a</td><td>11,3</td><td>Sustituto del gas R-12</td></tr><tr><td>R-407c</td><td>11,3</td><td>Refrigeración comercial e industrial AC</td></tr><tr><td>R-408a</td><td>10,9</td><td>Baja temperatura de refrigeración</td></tr><tr><td>R-410a</td><td>11,3</td><td>Refrigeración comercial e industrial AC</td></tr><tr><td>R-507</td><td>11,3</td><td>Baja temperatura de refrigeración</td></tr></table>"],
	["tub","Tubería recocida","tub/tubRec.jpg","Fabricados sin costura, de temple blando (recocido), cuya presentación es en rollos de 15 metros aprox.</br></br> <b>Aplicaciones:</b></br>Por su ductilidad y fácil adaptación se aplica con un mínimo de uniones (conexiones de cobre), en sistemas de refrigeración y aire acondicionado,  en áreas de superficie irregular o con obstáculos, sin necesidad de removerlos.</br></br><b>Medidas</b></br></br><table><tr><th>Pulgadas</th><th>Milimetros</th><th>EP</th><th>A</th></tr><tr><td>1/4\"</td><td>6.35</td><td>0.76</td><td>1.79</td></tr><tr><td>5/16\"</td><td>7.94</td><td>0.81</td><td>2.43</td></tr><tr><td>3/8\"</td><td>9.53</td><td>0.81</td><td>2.97</td></tr><tr><td>1/2\"</td><td>12.70</td><td>0.81</td><td>4.05</td></tr><tr><td>5/8\"</td><td>15.90</td><td>0.89</td><td>5.61</td></tr><tr><td>3/4\"</td><td>19.10</td><td>1.07</td><td>8.10</td></tr><tr><td>7/8\"</td><td>22.22</td><td>1.14</td><td>10.10</td></tr></table>"],
	["tub","Soldadura y componentes:","tub/tubSol.jpg","Las aleaciones para soldadura de aporte con antorcha o soplete de oxi-gas, cuyo proceso es conocido de manera general como “brazing”, se clasifican en dos grandes grupos: soldaduras cobre-fósforo de bajo contenido de plata, las soldaduras con alto contenido de plata (popularmente conocidas simplemente como \"plata\") base cobre. Las primeras son usadas fundamentalmente en las industrias de la refrigeración y el aire acondicionado para soldar tuberías de cobre, mientras que las segundas tienen un uso industrial más amplio; que van desde la soldadura de tuberías de acero ordinario o inoxidables, rellenado de elementos de máquinas para reparaciones, soldadura de metales disimilares.</br></br> <b>SP-2:</b>  Aleación con bajo contenido de plata (2%), para soldar COBRE-COBRE.</br></br><b>SP-6:</b>  Aleación con contenido de plata al 6%. Excelente para soldar COBRE-COBRE, o COBRE CON SUS ALEACIONES.</br> Especial para uniones de tuberías de refrigeración sometidas a exigencias normales de trabajo-presión y vibraciones. Para soldar COBRE-BRONCE aplicar fundente.</br></br><b>SP-15:</b> Contiene un 15% de plata, recomendada para la soldadura de COBRE-COBRE, o COBRE CON SUS ALEACIONES, especialmente en uniones sometidas a altas exigencias de trabajo-presión y/o vibraciones intensas.</br></br><b>SP-35-2S:</b> Aleación apropiada para soldaduras fuertes de COBRE-ACERO, ACERO INOXIDABLE, NÍQUEL, ALEACIONES DE NIQUEL, METALES PRECIOSOS. Contiene un 35% de plata. DEBE APLICARSE CON FUNDENTE."],
	["tub","Fundente Argenta","tub/tubFun.jpg","En pote de 50 gramos."],
	["sep","Tubo recibidor","sep/sepTub.jpg","Disponibles en distintas medidas:</br></br><table><tr><th rowspan=\"2\">Modelo N</th><th colspan=\"2\">Dimensiones(inch)</th><th rowspan=\"2\">Largo al<br>interior del<br>tubo</th><th rowspan=\"2\">Largo<br>fuera del<br>tubo</th><th rowspan=\"2\">Volumen</th></tr><tr><th>Dia . A</th><th>Shell b<br>Largo</th></tr><tr><td>CR-101-2</td><td>3.35</td><td>7.87</td><td>3/8</td><td>1/4</td><td>0.95</td></tr><tr><td>CR-101-3</td><td>3.35</td><td>7.87</td><td>3/8</td><td>3/8</td><td>0.95</td></tr><tr><td>CR-102</td><td>5.00</td><td>10.24</td><td>3/8</td><td>3/8</td><td>3.00</td></tr><tr><td>CR-103</td><td>5.00</td><td>11.81</td><td>3/8</td><td>3/8</td><td>3.40</td></tr><tr><td>CR-104</td><td>6.00</td><td>13.78</td><td>1/2</td><td>1/2</td><td>5.90</td></tr><tr><td>CR-105</td><td>7.00</td><td>16.15</td><td>5/8</td><td>5/8</td><td>9.55</td></tr><tr><td>CR-106</td><td>6.5</td><td>23.63</td><td>3/4</td><td>3/4</td><td>11.45</td></tr><tr><td>CR-107</td><td>6.5</td><td>27.56</td><td>7/8</td><td>7/8</td><td>15.47</td></tr></table>"],
	["sep","Separadores de liquido","sep/sepLiq.jpg","El papel del separador de líquido radica en la protección del compresor contra una migración accidental, por la tubería de aspiración, del refrigerante no vaporizado, que puede provocar un “golpe de líquido”, cuyos efectos perjudiciales pueden ir hasta la rotura mecánica del compresor. Los mismos efectos perjudiciales pueden venir también de un flujo brutal a la aspiración del compresor, por causa de tapones de aceite colocados en el evaporador o en las tuberías.</br></br>Este separador asegura la re evaporación y la aspiración por el compresor del refrigerante y el retorno al compresor del aceite retenido en la parte baja del separador.El refrigerante líquido cae al fondo del separador y se va a vaporizar por la aportación de calor exterior; el separador lleva un tubo de aspiración con un agujero en la parte baja. Cuando pasa por este orificio, hay una expansión del refrigerante, que se transforma en vapor y está re aspirado por el compresor; mientras el aceite que se ha quedado líquido está aspirado también con el refrigerante a través de esta apertura.</br></br><table><tr><th>Model N</th><th>Tamaño Conn</th><th>Dia A</th><th>Largo Shell B</th><th colspan=\"2\">Largo Sheel C</th><th>D</th><th>Volume&nbsp;</th></tr><tr><td>RA-204</td><td>1/2\"</td><td rowspan=\"2\">4</td><td>8.47</td><td colspan=\"2\">1.38</td><td>2.12</td><td>1.39</td></tr><tr><td>RA-205</td><td>5/8\"</td><td>10.83</td><td colspan=\"2\">1.38</td><td>2.12</td><td>1.90</td></tr><tr><td>RA-206</td><td>3/4\"</td><td rowspan=\"2\">5.5</td><td>10.24</td><td colspan=\"2\">1.58</td><td>3.15</td><td>3.50</td></tr><tr><td>RA-207</td><td>7/8\"</td><td>12.6</td><td colspan=\"2\">1.58</td><td>3.15</td><td>4.36</td></tr><tr><td>RA-211</td><td>11/8\"</td><td rowspan=\"3\">6.5</td><td>15.75</td><td colspan=\"2\">1.78</td><td>3.15</td><td>7.40</td></tr><tr><td>RA-213</td><td>13/8\"</td><td>20.87</td><td colspan=\"2\">1.78</td><td>3.31</td><td>9.90</td></tr><tr><td>RA-215</td><td>15/8\"</td><td>22.84</td><td colspan=\"2\">1.97</td><td>3.23</td><td>10.90</td></tr><tr><td colspan=\"4\" rowspan=\"2\"></td><th colspan=\"3\">Foot Stand<br>Hole distance</th><td rowspan=\"2\"></td></tr><tr><th>C</th><th>D</th><th>E</th></tr><tr><td>RA-221 B&nbsp;</td><td>2 1/8\"</td><td rowspan=\"2\">8.5</td><td>29.53</td><td>2.37</td><td>6.89</td><td>16.93</td><td>24.20</td></tr><tr><td>RA-225 B</td><td>2 5/8\"</td><td>33.47</td><td>2.76</td><td>6.89</td><td>16.93</td><td>27.00</td></tr><tr><td>RA-231 B</td><td>3 1/8\"</td><td>10.75</td><td>27.96</td><td>2.76</td><td>8.08</td><td>16.93</td><td>35.00</td></tr></table>"],
	["res","Resistencias Rigidas","res/resRig.jpg","Resistencias calefactoras rígidas en varillas dobles</br></br><b>Rígidas:</b></br></br>- Para deshielo de evaporadores.</br>- Resistencias tubulares de acero.</br>- 8.0 mm de diámetro.</br>- Desde 600 mm a 4000mm.</br>- De 240 a 3200 Watts."],
	["res","Resistencias Flexibles","res/resFlex.jpg","<b>Resistencias malla metálica:</b></br></br>- Desde 2,5, y 11 metros de largo.</br>- Desde 55 W hasta 250 Watts.</br></br><b>Potencia constante:</b></br></br>- 30w por metro lineal </br>- Rollos de 50 metros </br>-Termoretractil Inicio-Fin</br>"],


	["val" , "Válvula Solenoide", "val/valPaso.png", " Desde 1/4\" hasta 1,3/8\" conexiones a soldar o roscar"],
	["val" , "Válvula Retención NVRH ", "val/valPaso.png", " Desde 1/4\" hasta 1.5/8\" conexiones soldar o roscar "],
	["val" , "Válvula reguladora KVP", "val/valPaso.png", " Reguladora presion evaporacion 1/2\" hasta 1,3/8\""],
	["val" , "Válvula Reguladora KVL", "val/valPaso.png", " Reguladora de presion de carter 1/2\" hasta 1.3/8\""],
	["val" , "Válvula Rotalock", "val/valPaso.png", " Válvula de servicio desde 1/2\" a 1,3/8\""],
	["val" , "Válvula de Expansion", "val/valPaso.png", " Para refrigerante R-22/R407; R-134; R-507/ R-404;R-502 Cuerpo T2 hasta TE-55 "],
	["val" , "Válvula de paso BML", "val/valPaso.png", " Válvula de paso soldar o roscar desde 1/4\" hasta 7/8\""],
	["val" , "Válvula de paso GBC", "val/valPaso.png", " Válvula de paso desde 1/4\" hasta 3.1/8\""],
	["val" , "Valvula reguladora KVC", "val/valPaso.png", " Reguladora by pass gas caliente"],
	["val" , "Válvula reguladora de agua", "val/valPaso.png", " Desde 1/2\" a 1.1/2\""],
	["val" , "Válvula de seguridad", "val/valPaso.png", " Hasta 500 psi, conexiones 3/8 x 3/8 y 1/2 x 5/8"],
	["val" , "Válvula Reversible", "val/valPaso.png", " Desde 9000 BTU/h hasta 90.000 BTU/h"],


	["her" , " Cortadores de tubo ", "tools/tools/martillo.png", " De 1/8\" a 2-5/8\""],
	["her" , " Llaves de chicharra ", "tools/tools/martillo.png", " De 1/4\", 3/8\", 3/16\", 9/16\", 3/16\", 5/16\" y 1/2\" "],
	["her" , " Peine de aletas ", "tools/tools/martillo.png", " Para condensadores y evaporadores "],
	["her" , " Prensas de expansión ", "tools/tools/martillo.png", " De 1/4\" a 1-1/8\""],
	["her" , "Resorte dobla tubo", "tools/tools/martillo.png", "1/4\", 5/16\", 3/8\", 1/2\" y 5/8\""],
	["her" , " Saca pepas ", "tools/tools/martillo.png", " En cuerpo de aluminio y tubo de acero "],
	["her" , " Dobladora de tubos ", "tools/tools/martillo.png", "1/4\", 5/16\", 3/8\",1/2\", 5/8\", 7/8\" "],
	["her" , " Escariadores ", "tools/tools/martillo.png", " Para tuberías "],
	["her" , " Expandidores de golpe ", "tools/tools/martillo.png", " De 1/8\" a 7/8\" "],
	["her" , " Arboles de carga ", "tools/tools/martillo.png", " Para gases refrigerantes R22, R-134, R-404, R-507. Con y sin protector. digital y análogo "],
	["her" , " Bomba de Aceite ", "tools/tools/martillo.png", " Para carga de aceite "],
	["her" , " Corta capilar ", "tools/tools/martillo.png", " Herramienta de corte corta capilares "],
	["her" , " Soplete ", "tools/tools/martillo.png", " Antorcha de soldadura con encendido eléctrico y manual "],
	["her" , " Acople Rapido ", "tools/tools/martillo.png", " Herramienta para la carga de refrigerante en automóviles "],
	["her" , " Amperimetros ", "tools/tools/martillo.png", " Digitales y análogos "],
	["her" , " Caiman Sellador ", "tools/tools/martillo.png", ""],
	["her" , " Balanzas ", "tools/tools/martillo.png", " Electrónicas para la carga de refrigerante "],
	["her" , " Bomba de vacio ", "tools/tools/martillo.png", " Desde 3,5CFM a 12CFM "],
	["her" , "", "tools/tools/martillo.png", ""],


	["acc" , " Manómetros ", "tools/accesories/tubos.png", " de alta y baja  presión con  glicerina y sin glicerina "],
	["acc" , " Protectores de goma ", "tools/accesories/tubos.png", " Para la protección del manómetro "],
	["acc" , " Cuerpo o manifold ", "tools/accesories/tubos.png", " Cuerpo de 1 manómetro y 2 manómetros  de bronce, con visor "],
	["acc" , " Mangueras de carga ", "tools/accesories/tubos.png", " De 90 cm, 1.20 mts y 1.50 mts "],
	["acc" , " Acoples rápidos ", "tools/accesories/tubos.png", " Para aire acondicionado de automóviles. Modelos en alta y baja. Medidas 1/4\" y 5/16\"."],
	["acc" , " Adaptador de carga ", "tools/accesories/tubos.png", ": Adaptador para R-410 de 1/4\" a 5/16\" "],
	["acc" , " Repuestos para mangueras", "tools/accesories/tubos.png", ""],
	["acc" , " Map Gas ", "tools/accesories/tubos.png", " Cilindro para soldar de 400 grs "],
	["acc" , " Llave de pinche ", "tools/accesories/tubos.png", ""]

	
]

type_list.each do |model, sub_model , image , description|
  Category.create( model:model, sub_model:sub_model, description:description ,image:image)
end


product_list = [
	["Prod 1" , 100,"", 1 , "Buen Prod"],
	["Prod 2" , 100 ,"" ,1 , "Buen Prod"],
	["Prod 3", 100 ,"", 1 , "Buen Prod"],
	["Prod 4", 100 ,"" ,2 , "Buen Prod"],
	["Prod 5", 100 , "" , 2 , "Buen Prod"]
]

product_list.each do |name, price , image , category_id , description|
  Product.create( name:name, price:price ,image:image , category_id:category_id , description:description)
end

